config/routes.rb
Rails.application.routes.draw do
  # root_path of app
  root "buildings#index"

  # admin - building
  get "adminBuildings" => "administration#buildings"
  #admin - courses
  get "adminCourses" => "administration#courses"
  # admin - lessons
  get "adminLessons" => "administration#lessons"
  # admin - teachers
  get "adminTeachers" => "administration#teachers"
  get "adminTeacherAssignments" => "administration#teacherAssignments"
  # admin - students
  get "adminStudents" => "administration#students"
  get "adminStudentAssignments" => "administration#studentAssignments"
  # admin - rooms
  get "adminRooms" => "administration#rooms"
  # administration
  get "administration" => "administration#index"
  # login page
  # get "teacherLogin" => "teacher#login"
  get "login" => "logins#login"
  # resources :logins, only: [:login]
  get "logout" => "sessions#destroy"
  # post "logout" => "sessions#destroy"
  get "buildingSchedule/:id" => "buildings#schedule", as: "schedule"
  resources :sessions

  resources :student_assignments
  resources :student_attendances
  resources :teacher_assignments
  resources :administration
  resources :buildings
  resources :courses
  resources :teachers
  resources :lessons
  resources :rooms
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  # https://guides.rubyonrails.org/association_basics.html
  # 1:n - building x rooms
  has_many :rooms, dependent: :destroy

  # validations
  # VALID_PHONE_REGEX = /\A\d{3}-\d{3}-\d{3}\z/
  validates :title, :code, :description, presence: true
  validates :code, :title, uniqueness: {:case_sensitive => false}
end

app/models/course.rb
class Course < ApplicationRecord
  # m:n - course x teacher, course x student
  has_many :teacher_assignments, dependent: :destroy
  has_many :student_assignments, dependent: :destroy
  has_many :teacher, through: :teacher_assignments
  has_many :students, through: :student_assignments
  # 1:n - course x lesson
  has_many :lessons, dependent: :destroy #, as: :lessonable

  enum studytype: [:FULL_TIME, :PART_TIME]
  enum language: [:CZECH, :ENGLISH]

  extend Enumerize

  enumerize :study_type, in: [:FULL_TIME, :PART_TIME]
  enumerize :language_type, in: [:CZECH, :ENGLISH]

  # validations
  validates :title, :code, :language_type, :study_type, presence: true
  validates :code, :title, uniqueness: {:case_sensitive => false}
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  # 1:n - lesson x teacher, lesson x room, lesson x course
  # belongs_to :lessonable, :polymorphic => true
  belongs_to :course
  belongs_to :teacher
  belongs_to :room
  # m:n - student x lesson
  has_many :students, through: :student_attendances

  # validations
  validates :start_at, :end_at, :duration, :room_id, :teacher_id, :course_id, presence: true
  validates :duration, presence: true, numericality: {greater_than: 0}
end

app/models/room.rb
class Room < ApplicationRecord
  # 1:n building x room, room x lesson
  belongs_to :building
  has_many :lessons #, as: :lessonable

  # validations
  validates :title, :code, :building_id, :capacity, presence: true
  validates :capacity, numericality: {greater_than: 0}
  validates :code, :title, uniqueness: {:case_sensitive => false}
end

app/models/student.rb
class Student < ApplicationRecord
  has_secure_password

  # 1:n student_assignment x student
  has_many :student_assignments , dependent: :destroy
  # m:n student x course, student x lesson
  has_many :courses, through: :student_assignments
  has_many :lessons, through: :student_attendances

  enum studytype: [:FULL_TIME, :PART_TIME]

  extend Enumerize

  enumerize :study_type, in: [:FULL_TIME, :PART_TIME]

  # validations
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :first_name, :last_name, :email, :study_type, :password, presence: true
  validates :email, format: {with: VALID_EMAIL_REGEX}, uniqueness: {:case_sensitive => false}
end

app/models/student_assignment.rb
class StudentAssignment < ApplicationRecord
  # 1:n student_assignment x course, student_assignment x student
  belongs_to :course
  belongs_to :student

  # validations
  validates :course_id, :student_id, presence: true
end

app/models/student_attendance.rb
class StudentAttendance < ApplicationRecord
  # 1:n - lesson x studentAttendance, student x studentAttendance
  belongs_to :lesson
  belongs_to :student

  # validations
  validates :lesson_id, :student_id, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_secure_password
  # 1:n - teacher x lesson, teacher x teacher_assignment
  has_many :lessons #, as: :lessonable
  has_many :teacher_assignments, dependent: :destroy
  # m:n - teacher x course
  has_many :courses, through: :teacher_assignments

  # validations
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :first_name, :last_name, :email, :password, presence: true
  validates :email, format: {with: VALID_EMAIL_REGEX}, uniqueness: {:case_sensitive => false}
end

app/models/teacher_assignment.rb
class TeacherAssignment < ApplicationRecord
  # 1:n - teacher x teacherAssignment, course x teacherAssignment
  belongs_to :teacher
  belongs_to :course

  # validations
  validates :course_id, :teacher_id, presence: true
end

app/controllers/administration_controller.rb
class AdministrationController < ApplicationController
  before_action :require_login
  def index

  end

  # building CRUD
  def buildings # show buildings
    @buildings_data = Building.all
  end


  # Course CRUD
  def courses
    @courses = Course.all
  end
  # Lesson CRUD
  def lessons
    @lessons = Lesson.all.includes(:room,:teacher,:course)
  end

  #Teachers CRUD
  def teachers
    @teachers = Teacher.all
  end

  # Students CRUD
  def students
    @students = Student.all
  end

  # Rooms CRUD
  def rooms
    @rooms = Room.all.includes(:building)
  end

  def studentAssignments
    @studentAssignments = StudentAssignment.all.includes(:student, :course)
  end

  def teacherAssignments
    @teacherAssignments = TeacherAssignment.all.includes(:teacher, :course)
  end



end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
  def index
    @rooms = Room.all.includes(:building)
  end

  def new
    @rooms = Room.new
  end

  def show
    @room = Room.find(params[:id])
  end

  def create
    room = Room.new(room_params)
    if room.save
      redirect_to :adminRooms
    else
      flash[:errors] = room.errors.full_messages
      redirect_to new_room_path
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    room = Room.find(params[:id])
    if room.update(room_params)
      redirect_to :adminRooms
    else
      flash[:errors] = room.errors.full_messages
      redirect_to edit_room_path(room.id)
    end
  end

  def destroy
    Room.destroy(params[:id])
    redirect_to :adminRooms
  end


  # parameters
  def room_params
    params.require(:room).permit(:code, :title, :building_id, :capacity)
  end
end

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/administration/buildings.html.erb
<% content_for(:title, "Administration - Buildings") %>

<main class="main">
  <%=  render 'layouts/adminMenu'%>

  <div>
    <div class="center-me">
    <% if flash[:errors] %>
      <% flash[:errors].each do |e|%>
        <p><%= e %></p>
      <% end %>
    <%end %>
  </div>
    <div class="grid-schedule">
      <h1>Buildings - <%= link_to "Create new building", new_building_path, class: "admin-link" %></h1>
      <section class="grid-table">
        <% if @buildings_data.count < 1 %>
          <h1><%= "Databaze neobsahuje zadne zaznamy." %></h1>
       <% else %>
        <table class="table-schedule">
          <thead>
          <tr class="table-head">
            <th>ID</th>
            <th>Code</th>
            <th>Title</th>
            <th>Description</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          </thead>
          <tbody>
          <% @buildings_data.each do |building| %>
            <tr class="tr-hover">
              <td><%= building.id %></td>
              <td><%= building.code %></td>
              <td><%= building.title %></td>
              <td><%= building.description %></td>
              <td><%= link_to "Edit", edit_building_path(building.id), class: "admin-link" %></td>
              <td>
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <%= link_to "Delete", building_path(id: building.id, authenticity_token: form_authenticity_token), data: {method: :delete, confirm: "are you sure?"}, class: "admin-link" %></td>
            </tr>
          <% end %>

          </tbody>
        </table>
        <% end %>
      </section>
    </div>

  </div>

</main>

app/views/administration/courses.html.erb
<% content_for(:title, "Administration - Courses") %>

<main class="main">
  <%= render 'layouts/adminMenu' %>
  <div>
    <% if flash[:errors] %>
      <% flash[:errors].each do |e| %>
        <p><%= e %></p>
      <% end %>
    <% end %>

    <div class="grid-schedule">
      <h1>Courses - <%= link_to "Create new course", new_course_path, class: "admin-link" %></h1>
      <section class="grid-table">
        <% if @courses.count < 1 %>
          <h1><%= "Databaze neobsahuje zadne zaznamy." %></h1>
        <% else %>
        <table class="table-schedule">
          <thead>
          <tr class="table-head">
            <th>ID</th>
            <th>Code</th>
            <th>Title</th>
            <th>Language</th>
            <th>Study type</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          </thead>
          <tbody>
          <% @courses.each do |course| %>
            <tr class="tr-hover">
              <td><%= course.id %></td>
              <td><%= course.code %></td>
              <td><%= course.title %></td>
              <td><%= course.language_type %></td>
              <td><%= course.study_type %></td>
              <td><%= link_to "Edit", edit_course_path(course.id), class: "admin-link" %></td>
              <td>
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <%= link_to "Delete", course_path(id: course.id, authenticity_token: form_authenticity_token), data: {method: :delete, confirm: "are you sure?"}, class: "admin-link" %>
              </td>
            </tr>
          <% end %>

          </tbody>
        </table>
          <% end %>
      </section>
    </div>

  </div>

</main>

app/views/administration/index.html.erb
<% content_for(:title, "Administration - dashboard") %>

<main class="main">
  <%= render 'layouts/adminMenu' %>


  <div class="admin-wrapper">
    <section class="container-flex">
      <article class="flex-article link-color">

        <a href="<%= adminBuildings_path %>" class="admin-href">
          <p class="admin-h3"><%= Building.all.count %> Buildings</p>
        </a>
      </article>

      <article class="flex-article link-color">
        <a href="<%= adminRooms_path %>" class="admin-href">
          <p class="admin-h3"><%= Room.all.count %> Rooms</p>
        </a>
      </article>

      <article class="flex-article link-color">
        <a href="<%= adminTeachers_path %>" class="admin-href">
          <p class="admin-h3"><%= Teacher.all.count %> Teachers</p>
        </a>
      </article>

      <article class="flex-article link-color">
        <a href="<%= adminStudents_path %>" class="admin-href">
          <p class="admin-h3"><%= Student.all.count %> Students</p>
        </a>
      </article>

      <article class="flex-article link-color">
        <a href="<%= adminLessons_path %>" class="admin-href">
          <p class="admin-h3"><%= Lesson.all.count %> Lessons</p>
        </a>
      </article>

      <article class="flex-article link-color">
        <a href="<%= adminCourses_path %>" class="admin-href">
          <p class="admin-h3"><%= Course.all.count %> Courses</p>
        </a>
      </article>

      <article class="flex-article link-color">
        <a href="<%= adminTeacherAssignments_path %>" class="admin-href">
          <p class="admin-h3"><%= TeacherAssignment.all.count %> Assigned Teachers</p>
        </a>
      </article>

      <article class="flex-article link-color">
        <a href="<%= adminStudentAssignments_path %>" class="admin-href">
          <p class="admin-h3"><%= StudentAssignment.all.count %> Assigned Students</p>
        </a>
      </article>
    </section>

  </div>
  <div class="grid-articles">

  </div>

</main>

app/views/administration/lessons.html.erb
<% content_for(:title, "Administration - Lessons") %>

<main class="main">
  <%=  render 'layouts/adminMenu'%>

  <div>
    <% if flash[:errors] %>
      <% flash[:errors].each do |e|%>
        <p><%= e %></p>
      <% end %>
    <%end %>

    <div class="grid-schedule">
      <h1>Lessons - <%= link_to "Create new lesson", new_lesson_path, class: "admin-link" %></h1>
      <section class="grid-table">
        <% if @lessons.count < 1 %>
          <h1><%= "Databaze neobsahuje zadne zaznamy." %></h1>
        <% else %>
        <table class="table-schedule">
          <thead>
          <tr class="table-head">
            <th>ID</th>
            <th>Start_at</th>
            <th>End_at</th>
            <th>Duration</th>
            <th>Room</th>
            <th>Teacher</th>
            <th>Course</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          </thead>
          <tbody>
          <% @lessons.each do |lesson| %>
            <tr class="tr-hover">
              <td><%= lesson.id %></td>
              <td><%= lesson.start_at %></td>
              <td><%= lesson.end_at %></td>
              <td><%= lesson.duration %></td>
              <td><%= lesson.room.title %></td>
              <td><%= lesson.teacher.first_name + " " + lesson.teacher.last_name %></td>
              <td><%= lesson.course.title %></td>
              <td><%= link_to "Edit", edit_lesson_path(lesson.id), class: "admin-link" %></td>
              <td>
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <%= link_to "Delete", lesson_path(id: lesson.id, authenticity_token: form_authenticity_token), data: {method: :delete, confirm: "are you sure?"}, class: "admin-link" %></td>
            </tr>
          <% end %>

          </tbody>
        </table>
          <%end %>
      </section>
    </div>

  </div>

</main>

app/views/administration/rooms.html.erb
<% content_for(:title, "Administration - Rooms") %>

<main class="main">
  <%=  render 'layouts/adminMenu'%>

  <div>
    <div class="grid-schedule">
      <h1>Rooms - <%= link_to "Create new room", new_room_path, class: "admin-link" %></h1>
      <section class="grid-table">
        <% if @rooms.count < 1 %>
          <h1><%= "Databaze neobsahuje zadne zaznamy." %></h1>
        <% else %>
        <table class="table-schedule">
          <thead>
          <tr class="table-head">
            <th>ID</th>
            <th>Code</th>
            <th>Title</th>
            <th>Building-title</th>
            <th>Capacity</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          </thead>
          <tbody>
          <% @rooms.each do |room| %>
            <tr class="tr-hover">
              <td><%= room.id %></td>
              <td><%= room.code %></td>
              <td><%= room.title %></td>
              <td><%= room.building.title %></td>
              <td><%= room.capacity %></td>
              <td><%= link_to "Edit", edit_room_path(room.id), class: "admin-link" %></td>
              <td>
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <%= link_to "Delete", room_path(id: room.id, authenticity_token: form_authenticity_token), data: {method: :delete, confirm: "are you sure?"}, class: "admin-link" %></td>
            </tr>
          <% end %>

          </tbody>
        </table>
          <%end %>
      </section>
    </div>

  </div>

</main>

app/views/administration/studentAssignments.html.erb
<% content_for(:title, "Administration - Students") %>

<main class="main">
  <%=  render 'layouts/adminMenu'%>

  <div>
    <% if flash[:errors] %>
      <% flash[:errors].each do |e|%>
        <p><%= e %></p>
      <% end %>
    <%end %>

    <div class="grid-schedule">
      <h1>Student Assignments - <%= link_to "Create new Student assignment", new_student_assignment_path, class: "admin-link" %></h1>
      <section class="grid-table">
        <% if @studentAssignments.count < 1 %>
          <h1><%= "Databaze neobsahuje zadne zaznamy." %></h1>
        <% else %>
        <table class="table-schedule">
          <thead>
          <tr class="table-head">
            <th>ID</th>
            <th>Student</th>
            <th>Course</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          </thead>
          <tbody>
          <% @studentAssignments.each do |assignment| %>
            <tr class="tr-hover">
              <td><%= assignment.id %></td>
              <td><%= assignment.student.first_name + " " +  assignment.student.last_name%></td>
              <td><%= assignment.course.title %></td>
              <td><%= link_to "Edit", edit_student_assignment_path(assignment.id), class: "admin-link" %></td>
              <td>
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <%= link_to "Delete", student_assignment_path(id: assignment.id, authenticity_token: form_authenticity_token), data: {method: :delete, confirm: "are you sure?"}, class: "admin-link" %></td>
            </tr>
          <% end %>

          </tbody>
        </table>
          <% end %>
      </section>
    </div>

  </div>

</main>

app/views/administration/students.html.erb
<% content_for(:title, "Administration - Students") %>

<main class="main">
  <%=  render 'layouts/adminMenu'%>

  <div>
    <% if flash[:errors] %>
      <% flash[:errors].each do |e|%>
        <p><%= e %></p>
      <% end %>
    <%end %>

    <div class="grid-schedule">
      <h1>Students - <%= link_to "Create new student", new_student_path, class: "admin-link" %></h1>
      <section class="grid-table">
        <% if @students.count < 1 %>
          <h1><%= "Databaze neobsahuje zadne zaznamy." %></h1>
        <% else %>
        <table class="table-schedule">
          <thead>
          <tr class="table-head">
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Study type</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          </thead>
          <tbody>
          <% @students.each do |student| %>
            <tr class="tr-hover">
              <td><%= student.id %></td>
              <td><%= student.first_name %></td>
              <td><%= student.last_name %></td>
              <td><%= student.email %></td>
              <td><%= student.study_type %></td>
              <td><%= link_to "Edit", edit_student_path(student.id), class: "admin-link" %></td>
              <td>
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <%= link_to "Delete", student_path(id: student.id, authenticity_token: form_authenticity_token), data: {method: :delete, confirm: "are you sure?"}, class: "admin-link" %></td>
            </tr>
          <% end %>

          </tbody>
        </table>
          <%end %>
      </section>
    </div>

  </div>

</main>

app/views/administration/teacherAssignments.html.erb
<% content_for(:title, "Administration - Teachers") %>

<main class="main">
  <%=  render 'layouts/adminMenu'%>

  <div>
    <% if flash[:errors] %>
      <% flash[:errors].each do |e|%>
        <p><%= e %></p>
      <% end %>
    <%end %>

    <div class="grid-schedule">
      <h1>Teacher Assignments - <%= link_to "Create new teacher assignment", new_teacher_assignment_path, class: "admin-link" %></h1>
      <section class="grid-table">
        <% if @teacherAssignments.count < 1 %>
          <h1><%= "Databaze neobsahuje zadne zaznamy." %></h1>
        <% else %>
        <table class="table-schedule">
          <thead>
          <tr class="table-head">
            <th>ID</th>
            <th>Teacher</th>
            <th>Course</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          </thead>
          <tbody>
          <% @teacherAssignments.each do |assignment| %>
            <tr class="tr-hover">
              <td><%= assignment.id %></td>
              <td><%= assignment.teacher.first_name + " " +  assignment.teacher.last_name%></td>
              <td><%= assignment.course.title %></td>
              <td><%= link_to "Edit", edit_teacher_assignment_path(assignment.id), class: "admin-link" %></td>
              <td>
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <%= link_to "Delete", teacher_assignment_path(id: assignment.id, authenticity_token: form_authenticity_token), data: {method: :delete, confirm: "are you sure?"}, class: "admin-link" %></td>
            </tr>
          <% end %>

          </tbody>
        </table>
          <%end %>
      </section>
    </div>

  </div>

</main>

app/views/administration/teachers.html.erb
<% content_for(:title, "Administration - Students") %>

<main class="main">
  <%=  render 'layouts/adminMenu'%>

  <div>
    <% if flash[:errors] %>
      <% flash[:errors].each do |e|%>
        <p><%= e %></p>
      <% end %>
    <%end %>

    <div class="grid-schedule">
      <h1>Teachers - <%= link_to "Create new teacher", new_teacher_path, class: "admin-link" %></h1>
      <section class="grid-table">
        <% if @teachers.count < 1 %>
          <h1><%= "Databaze neobsahuje zadne zaznamy." %></h1>
        <% else %>
        <table class="table-schedule">
          <thead>
          <tr class="table-head">
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          </thead>
          <tbody>
          <% @teachers.each do |teacher| %>
            <tr class="tr-hover">
              <td><%= teacher.id %></td>
              <td><%= teacher.first_name %></td>
              <td><%= teacher.last_name %></td>
              <td><%= teacher.email %></td>
              <td><%= link_to "Edit", edit_teacher_path(teacher.id), class: "admin-link" %></td>
              <td>
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <%= link_to "Delete", teacher_path(id: teacher.id, authenticity_token: form_authenticity_token), data: {method: :delete, confirm: "are you sure?"}, class: "admin-link" %></td>
            </tr>
          <% end %>

          </tbody>
        </table>
          <%end %>
      </section>
    </div>

  </div>

</main>