config/routes.rb
Rails.application.routes.draw do
  # root_path of app
  root "buildings#index"

  # admin - building
  get "adminBuildings" => "administration#buildings"
  #admin - courses
  get "adminCourses" => "administration#courses"
  # admin - lessons
  get "adminLessons" => "administration#lessons"
  # admin - teachers
  get "adminTeachers" => "administration#teachers"
  get "adminTeacherAssignments" => "administration#teacherAssignments"
  # admin - students
  get "adminStudents" => "administration#students"
  get "adminStudentAssignments" => "administration#studentAssignments"
  # admin - rooms
  get "adminRooms" => "administration#rooms"
  # administration
  get "administration" => "administration#index"
  # login page
  # get "teacherLogin" => "teacher#login"
  get "login" => "logins#login"
  # resources :logins, only: [:login]
  get "logout" => "sessions#destroy"
  # post "logout" => "sessions#destroy"
  get "buildingSchedule/:id" => "buildings#schedule", as: "schedule"
  resources :sessions

  resources :student_assignments
  resources :student_attendances
  resources :teacher_assignments
  resources :administration
  resources :buildings
  resources :courses
  resources :teachers
  resources :lessons
  resources :rooms
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  # https://guides.rubyonrails.org/association_basics.html
  # 1:n - building x rooms
  has_many :rooms, dependent: :destroy

  # validations
  # VALID_PHONE_REGEX = /\A\d{3}-\d{3}-\d{3}\z/
  validates :title, :code, :description, presence: true
  validates :code, :title, uniqueness: {:case_sensitive => false}
end

app/models/course.rb
class Course < ApplicationRecord
  # m:n - course x teacher, course x student
  has_many :teacher_assignments, dependent: :destroy
  has_many :student_assignments, dependent: :destroy
  has_many :teacher, through: :teacher_assignments
  has_many :students, through: :student_assignments
  # 1:n - course x lesson
  has_many :lessons, dependent: :destroy #, as: :lessonable

  enum studytype: [:FULL_TIME, :PART_TIME]
  enum language: [:CZECH, :ENGLISH]

  extend Enumerize

  enumerize :study_type, in: [:FULL_TIME, :PART_TIME]
  enumerize :language_type, in: [:CZECH, :ENGLISH]

  # validations
  validates :title, :code, :language_type, :study_type, presence: true
  validates :code, :title, uniqueness: {:case_sensitive => false}
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  # 1:n - lesson x teacher, lesson x room, lesson x course
  # belongs_to :lessonable, :polymorphic => true
  belongs_to :course
  belongs_to :teacher
  belongs_to :room
  # m:n - student x lesson
  has_many :students, through: :student_attendances

  # validations
  validates :start_at, :end_at, :duration, :room_id, :teacher_id, :course_id, presence: true
  validates :duration, presence: true, numericality: {greater_than: 0}
end

app/models/room.rb
class Room < ApplicationRecord
  # 1:n building x room, room x lesson
  belongs_to :building
  has_many :lessons #, as: :lessonable

  # validations
  validates :title, :code, :building_id, :capacity, presence: true
  validates :capacity, numericality: {greater_than: 0}
  validates :code, :title, uniqueness: {:case_sensitive => false}
end

app/models/student.rb
class Student < ApplicationRecord
  has_secure_password

  # 1:n student_assignment x student
  has_many :student_assignments , dependent: :destroy
  # m:n student x course, student x lesson
  has_many :courses, through: :student_assignments
  has_many :lessons, through: :student_attendances

  enum studytype: [:FULL_TIME, :PART_TIME]

  extend Enumerize

  enumerize :study_type, in: [:FULL_TIME, :PART_TIME]

  # validations
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :first_name, :last_name, :email, :study_type, :password, presence: true
  validates :email, format: {with: VALID_EMAIL_REGEX}, uniqueness: {:case_sensitive => false}
end

app/models/student_assignment.rb
class StudentAssignment < ApplicationRecord
  # 1:n student_assignment x course, student_assignment x student
  belongs_to :course
  belongs_to :student

  # validations
  validates :course_id, :student_id, presence: true
end

app/models/student_attendance.rb
class StudentAttendance < ApplicationRecord
  # 1:n - lesson x studentAttendance, student x studentAttendance
  belongs_to :lesson
  belongs_to :student

  # validations
  validates :lesson_id, :student_id, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_secure_password
  # 1:n - teacher x lesson, teacher x teacher_assignment
  has_many :lessons #, as: :lessonable
  has_many :teacher_assignments, dependent: :destroy
  # m:n - teacher x course
  has_many :courses, through: :teacher_assignments

  # validations
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :first_name, :last_name, :email, :password, presence: true
  validates :email, format: {with: VALID_EMAIL_REGEX}, uniqueness: {:case_sensitive => false}
end

app/models/teacher_assignment.rb
class TeacherAssignment < ApplicationRecord
  # 1:n - teacher x teacherAssignment, course x teacherAssignment
  belongs_to :teacher
  belongs_to :course

  # validations
  validates :course_id, :teacher_id, presence: true
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
  def index
    @buildings = Building.all
  end

  def new
    @buildings = Building.new
  end

  def show
    @building = Building.find(params[:id])
  end

  def schedule
    @building = Building.find(params[:id])
    @rooms = Room.where(building_id: params[:id]).includes(:lessons)
  end

  def create
    building = Building.new(building_params)
    if building.save
      redirect_to :adminBuildings
    else
      flash[:errors] = building.errors.full_messages
      redirect_to new_building_path
    end
  end

  def edit
    @building = Building.find(params[:id])
  end

  def update
    building = Building.find(params[:id])
    if building.update(building_params)
      redirect_to :adminBuildings
    else
      flash[:errors] = building.errors.full_messages
      redirect_to edit_building_path(building.id)
    end
  end

  def destroy
    Building.destroy(params[:id])
    redirect_to :adminBuildings
  end


  # parameters
  def building_params
    params.require(:building).permit(:code, :title, :description)
  end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def login

  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
  def index
    @rooms = Room.all.includes(:building)
  end

  def new
    @rooms = Room.new
  end

  def show
    @room = Room.find(params[:id])
  end

  def create
    room = Room.new(room_params)
    if room.save
      redirect_to :adminRooms
    else
      flash[:errors] = room.errors.full_messages
      redirect_to new_room_path
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    room = Room.find(params[:id])
    if room.update(room_params)
      redirect_to :adminRooms
    else
      flash[:errors] = room.errors.full_messages
      redirect_to edit_room_path(room.id)
    end
  end

  def destroy
    Room.destroy(params[:id])
    redirect_to :adminRooms
  end


  # parameters
  def room_params
    params.require(:room).permit(:code, :title, :building_id, :capacity)
  end
end

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/buildings/edit.html.erb
<% content_for(:title, "Administration - Buildings") %>

<main class="main">
  <%=  render 'layouts/adminMenu'%>





  <div class="center-me">
    <% if flash[:errors] %>
      <% flash[:errors].each do |e|%>
        <p><%= e %></p>
      <% end %>
    <%end %>

    <%= simple_form_for @building do |f| %>
      <%= f.input :code, label: "Building code goes here.", error: 'Code is mandatory, please specify one.'%>
      <%= f.input :title, label: "Building title goes here.", error: 'Title is mandatory, please specify one.'%>
      <%= f.input :description, label: "Building description goes here.", error: 'Description is mandatory, please specify one.'%>
      <%= f.button :submit %>
    <% end %>
  </div>

</main>

app/views/buildings/index.html.erb
<% content_for(:title, "Buildings") %>

<main class="main">
  <nav class="breadcrumbs">
    <ul class="breadcrumb">
      <li>Meeting Center</li>
    </ul>
  </nav>

  <div class="grid-articles">
    <% if flash[:errors] %>
      <% flash[:errors].each do |e|%>
        <p><%= e %></p>
      <% end %>
    <%end %>
    <section class="container-flex">
      <% if @buildings.count < 1 %>
        <h1><%= "Databaze neobsahuje zadne zaznamy." %></h1>
      <% else %>
      <% @buildings.each do |building| %>
        <article class="flex-article link-color">
          <%= link_to building_path(building.id) do %>
<!--          <a href="<%#= building_path/building.id %>" class="bs-link-fix">-->
            <img src="/assets/par1.1.jpg" alt="" class="room-img">
            <h3 class="brick-text-h3"><%= building.code %></h3>
            <h4 class="brick-text-h4"><%= building.title %></h4>
            <p class="brick-text"><%= building.description %></p>
<!--          </a>-->

            <%end %>
        </article>
      <% end %>
        <%end %>
    </section>
  </div>
</main>

app/views/buildings/new.html.erb
<% content_for(:title, "Administration - Buildings") %>
<main class="main">
  <%=  render 'layouts/adminMenu'%>

  <div class="center-me">
    <% if flash[:errors] %>
      <% flash[:errors].each do |e|%>
        <p><%= e %></p>
      <% end %>
    <%end %>

    <%= simple_form_for @buildings do |f| %>
      <%= f.input :code %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.button :submit %>
    <% end %>
  </div>

</main>

app/views/buildings/schedule.html.erb
<main class="main">
  <nav class="breadcrumbs">
    <ul class="breadcrumb">
      <li><a href="<%= root_path %>" class="link-bread">Meeting Center</a></li>
      <li><a href="<%= building_path(@building.id) %>" class="link-bread">Building</a></li>
      <li>Nazev: <%= @building.title %></li>
    </ul>
  </nav>
  <div class="grid-today">
    <div class="today-group">

      <h1>PAR 1.1 - Albrecht</h1>
      <p></p>
    </div>
    <img src="/assets/par1.1.jpg" alt="" class="today-img">
    <section class="today-schedule">
      <table class="table-schedule">
        <thead>
        <tr class="table-head">
          <th>Čas</th>
          <th>Předmět</th>
          <th>Místnost</th>
          <th>Vyučující</th>
          <th>Průběh</th>
        </tr>
        </thead>
        <tbody>
        <% empty = true %>
        <% @rooms.each do |r| %>
          <% if r.lessons.count < 1 %>
          <% else %>
            <% empty = false %>
            <% r.lessons.each do |l| %>
              <% if Date.current == l.start_at.to_date %>

                <tr class="tr-hover-today tr-text">
                  <td><%= l.start_at.strftime("%H:%M") %> - <%= l.end_at.strftime("%H:%M") %></td>
                  <td><%= l.course.title %> <br></td>
                  <td><%= r.title %></td>
                  <td><%= l.teacher.first_name + " " + l.teacher.last_name %></td>
                  <td>
                    <div class="progress-bar">

                      <div class="progress-bar-0">
                        <span class="progress-bar-text">0%</span>
                      </div>
                    </div>
                  </td>
                </tr>
              <% end %>
            <% end %>
          <% end %>

        <% end %>
        <% if empty %>
          <h1><%= "Databaze neobsahuje zadne zaznamy!" %></h1>
        <% end %>
        </tbody>
      </table>
    </section>
  </div>
</main>

app/views/buildings/show.html.erb
<% content_for(:title, "Buildings") %>


<main class="main">
  <nav class="breadcrumbs">
    <ul class="breadcrumb">
      <li><a href="<%= root_path %>" class="link-bread">Meeting Center</a></li>
      <li>Rooms</li>
    </ul>
  </nav>
  <div class="grid-rooms">

    <h1>Název: <%= @building.title %></h1>
    <section class="grid-room">
      <p>popis: <%= @building.description %></p>
      <address class="room-address-fixed">
        Kudy k nám: <a href="https://goo.gl/maps/MqumTj9hj9G2" class="address-link">Unicorn College -
        Parukářka</a><br>
        Adresa: V Kapslovně 2767/2, 130 00 Praha 3 <br>
        Tel: +420 271 097 111 <br>
      </address>

    </section>
    <section class="grid-room-reverse">

      <aside class="aside-schedule">
        <a href="<%= schedule_path(@building.id) %>" class="icon-link">
          <img src="/assets/schedule.png" alt="" class="schedule-icon"> Zobraz denní rozpis</a>

        <p>Pro zobrazení rozvrhu vyberte místnost</p>
        <ul>
          <% if @building.rooms.count > 0 %>
            <% @building.rooms.each do |r| %>
              <li>
                <%= r.title %> <%= link_to "Zobraz rozvrh", room_path(r.id) %>
              </li>
            <% end %>
          <% else %>
          <h4>Budova nema mistnosti!</h4>
          <% end %>
        </ul>
      </aside>
      <img src="/assets/parukarka.JPEG" alt="" class="img-building-fixed">

    </section>
  </div>
</main>